/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bean;

import java.awt.Color;

/**
 *
 * @author Leticia
 */
public class FormTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormTelaPrincipal
     */
    public FormTelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(new Color (255,204,204));
    }
    
    public void BtnSair(){
        //ação fechar programa
       System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        btnNovoCliente = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnAgendarServiço = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuCadastrarCliente = new javax.swing.JMenuItem();
        menuCadastrarAnimal = new javax.swing.JMenuItem();
        cadastrarUsuario = new javax.swing.JMenuItem();
        menuAgendamento = new javax.swing.JMenu();
        menuAgendar = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenu();
        menuAgenda = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuServiços = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        menuSairSistema = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pet Shop");
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(java.awt.Color.white);

        btnNovoCliente.setBackground(new java.awt.Color(255, 204, 204));
        btnNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensSistema/GatoCachorroBotao.png"))); // NOI18N
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnAgenda.setBackground(new java.awt.Color(255, 204, 204));
        btnAgenda.setText("Agenda");
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });

        btnAgendarServiço.setBackground(new java.awt.Color(255, 204, 204));
        btnAgendarServiço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensSistema/Imagem cachorro fundo rosa.jpg"))); // NOI18N
        btnAgendarServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarServiçoActionPerformed(evt);
            }
        });

        menuCadastrar.setText("Cadastrar");

        menuCadastrarCliente.setBackground(new java.awt.Color(255, 204, 204));
        menuCadastrarCliente.setText("Cliente");
        menuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarCliente);

        menuCadastrarAnimal.setBackground(new java.awt.Color(255, 204, 204));
        menuCadastrarAnimal.setText("Animal");
        menuCadastrarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarAnimalActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarAnimal);

        cadastrarUsuario.setBackground(new java.awt.Color(255, 204, 204));
        cadastrarUsuario.setText("Usuário");
        cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarUsuario);

        jMenuBar1.add(menuCadastrar);

        menuAgendamento.setText("Agendamento");

        menuAgendar.setBackground(new java.awt.Color(255, 204, 204));
        menuAgendar.setText("Agendar serviço");
        menuAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendarActionPerformed(evt);
            }
        });
        menuAgendamento.add(menuAgendar);

        jMenuBar1.add(menuAgendamento);

        menuConsultar.setText("Consultar");

        menuAgenda.setBackground(new java.awt.Color(255, 204, 204));
        menuAgenda.setText("Agenda");
        menuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendaActionPerformed(evt);
            }
        });
        menuConsultar.add(menuAgenda);

        menuClientes.setBackground(new java.awt.Color(255, 204, 204));
        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuConsultar.add(menuClientes);

        menuServiços.setBackground(new java.awt.Color(255, 204, 204));
        menuServiços.setText("Serviços/Preços");
        menuServiços.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiçosActionPerformed(evt);
            }
        });
        menuConsultar.add(menuServiços);

        menuUsuarios.setBackground(new java.awt.Color(255, 204, 204));
        menuUsuarios.setText("Usuários");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        menuConsultar.add(menuUsuarios);

        jMenuBar1.add(menuConsultar);

        menuOpcoes.setText("Opções");

        menuSairSistema.setText("Sair");
        menuSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairSistemaActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuSairSistema);

        jMenuBar1.add(menuOpcoes);

        menuRelatorios.setText("Relatórios");
        jMenuBar1.add(menuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgendarServiço)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNovoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgendarServiço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnAgenda)))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarClienteActionPerformed
        FormCadastrarClientes.main(null);
    }//GEN-LAST:event_menuCadastrarClienteActionPerformed

    private void menuServiçosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiçosActionPerformed
        TabelaServiços.main(null);
        
    }//GEN-LAST:event_menuServiçosActionPerformed

    private void menuCadastrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarAnimalActionPerformed
        FormCadastrarAnimais.main(null);
    }//GEN-LAST:event_menuCadastrarAnimalActionPerformed

    private void menuAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendarActionPerformed
       FormAgendamento.main(null);
    }//GEN-LAST:event_menuAgendarActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        FormCadastrarClientes.main(null);        
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void btnAgendarServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarServiçoActionPerformed
        FormAgendamento.main(null);        
    }//GEN-LAST:event_btnAgendarServiçoActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        TabelaAgenda.main(null);
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioActionPerformed
        FormCadastrarUsuarios.main(null);
    }//GEN-LAST:event_cadastrarUsuarioActionPerformed

    private void menuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendaActionPerformed
        TabelaAgenda.main(null);
    }//GEN-LAST:event_menuAgendaActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        TabelaUsuarios.main(null);
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        TabelaClientes.main(null);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairSistemaActionPerformed
        BtnSair();
    }//GEN-LAST:event_menuSairSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnAgendarServiço;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JMenuItem cadastrarUsuario;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuAgenda;
    private javax.swing.JMenu menuAgendamento;
    private javax.swing.JMenuItem menuAgendar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCadastrarAnimal;
    private javax.swing.JMenuItem menuCadastrarCliente;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuSairSistema;
    private javax.swing.JMenuItem menuServiços;
    private javax.swing.JMenuItem menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
